media:
  input: static/images
  output: /situsku/images

content:
  - name: articles
    label: Artikel
    type: collection
    path: content/articles
    filename: "{fields.title}.md"
    fields:
      - name: title
        label: Judul
        type: string
        required: true
      - name: date
        label: Tanggal
        type: date
        required: true
      - name: author
        label: Penulis
        type: string
        required: true
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: featured_image
        label: Gambar Unggulan
        type: image
        required: false
      - name: categories
        label: Kategori
        type: string
        list: true
        required: true
      - name: description
        label: Deskripsi
        type: text
        required: false
      - name: tags
        label: Tags
        type: string
        list: true
        required: false
      - name: body
        label: Konten
        type: rich-text
        required: true